### ISSUE TITLE
Cast to Pid on Monterey M1

### ISSUE THREAD

**Issue by Goffen** [rbspy/read-process-memory#18]
Hi there! This might be silly of me. Very new to rust. But I can't get the example to work properly

When I run exactly the same code as on the main page it crashes and gives me this:

Error: Os { code: 0, kind: Uncategorized, message: "Undefined error: 0" }

I've debugged and that happens on the TryInto 
`let handle: ProcessHandle = (&child).try_into().unwrap();`

I run macOS Monterey with M1 chip.

**Comment by luser** [comment]
Getting a Mach port from an existing PID is fiddly and Apple has locked it down tighter over the years. You might try using my [`spawn-task-port`](https://crates.io/crates/spawn-task-port) crate (which I admittedly haven't tested on Monterey or M1) to get one while launching a child process.

**Comment by acj** [comment]
@Goffen Can you try running it with `sudo`? I get that same error when I run the tests as a normal user, but `sudo cargo test` works fine.
